data_path: 'dataset/or-pantry/'
pq_data: OP
benchmark_filename: [train, valid, test]
alias_of_item_id: [item_id_list]
load_col:
  inter: [user_id, item_id_list, item_id]
neg_sampling: ~
transform: ~

topk: [10, 50]
metrics: [Recall, NDCG]
valid_metric: Recall@10
stopping_step: 10
gpu_id : 0
learning_rate: 0.001
epoch: 100

save_step: 10
train_batch_size: 1024

index_path: dataset/or-pantry
index_pretrain_dataset: P
filter_id_suffix: filtered_id
checkpoint_dir : 'save_OP/'