data_path: 'dataset/office-arts/'
pq_data: OA # 进行PQ索引时用的数据集缩写，比如如果是将“OR Pantry”一起进行索引的这里就是OP
benchmark_filename: [train, valid, test]
alias_of_item_id: [item_id_list]
load_col:
  inter: [user_id, item_id_list, item_id]
neg_sampling: ~
transform: ~

topk: [10, 50]
metrics: [Recall, NDCG]
valid_metric: Recall@10
stopping_step: 10
gpu_id : 0
learning_rate: 0.001
epoch: 100

train_stage: pretrain
pretrain_epochs: 100
save_step: 10
train_batch_size: 1024

index_path: dataset/office-arts
index_pretrain_dataset: A #进行微调的单个数据集
filter_id_suffix: filtered_id
checkpoint_dir : 'save_OA/'
